from pathlib import Path
import re,json
root=Path('/mnt/data/m28_final_work')
h=root/'index.html'; s=h.read_text(encoding='utf8')
# CSS additions
s=s.replace('button{border:0;border-radius:14px;padding:12px 15px;cursor:pointer;font-weight:800}', 'button{border:0;border-radius:14px;padding:12px 15px;cursor:pointer;font-weight:800;box-shadow:0 4px 0 #0b3b3822,0 8px 16px #0b3b3812;transform:translateY(0);transition:transform .12s,box-shadow .12s}button:active{transform:translateY(2px);box-shadow:0 2px 0 #0b3b3822,0 4px 8px #0b3b3812}button:disabled{box-shadow:none}')
s=s.replace('.severityWrap{position:relative;', '.severityWrap{position:relative;')
s=s.replace('.severityThumb{position:absolute;', '.severityValue{position:absolute;top:-28px;right:0;background:var(--navy);color:#fff;border-radius:7px;padding:2px 6px;font-size:10px;font-weight:800;line-height:1.4}.severityThumb{position:absolute;')
s=s.replace('.hidden{display:none!important}', '.floatingProfileBack{position:fixed;right:14px;bottom:14px;z-index:90;background:var(--navy);color:#fff;border:2px solid #ffffff66;border-radius:999px;padding:9px 12px;font-size:11px;box-shadow:0 8px 22px #102a4340}.hidden{display:none!important}.bookPreviewModal{position:fixed;inset:0;background:#0d393855;display:grid;place-items:center;padding:18px;z-index:105}.bookPreviewModal.hidden{display:none}.bookPreviewCard{max-width:560px;width:100%;max-height:82vh;overflow:auto;background:#fff;border-radius:22px;padding:20px;box-shadow:0 20px 60px #0d393844}.bookPreviewText{white-space:pre-wrap;line-height:2;font-size:13px;user-select:none;-webkit-user-select:none}')
# Replace scores with slider structures
s=s.replace('<label>وضعیت کلی من در حال حاضر از ۰ تا ۱۰</label><input id="aScore" type="number" min="0" max="10" step="1" inputmode="numeric" placeholder="۰ تا ۱۰">', '<label>وضعیت کلی من در حال حاضر از ۰ تا ۱۰</label><div class="severityWrap scoreControl"><div id="aScoreValue" class="severityValue">۵ از ۱۰</div><div id="aScoreThumb" class="severityThumb"></div><input id="aScore" class="severityRange" type="range" min="0" max="10" step="1" value="5" aria-label="وضعیت کلی"></div><div class="stats" style="color:var(--muted);margin-top:0"><span>۰ = خیلی کم</span><span>۵ = متوسط</span><span>۱۰ = خیلی شدید</span></div>')
s=s.replace('<label>وضعیت کلی من اکنون از ۰ تا ۱۰</label><input id="fScore" type="number" min="0" max="10" step="1" inputmode="numeric" placeholder="۰ تا ۱۰">', '<label>وضعیت کلی من اکنون از ۰ تا ۱۰</label><div class="severityWrap scoreControl"><div id="fScoreValue" class="severityValue">۵ از ۱۰</div><div id="fScoreThumb" class="severityThumb"></div><input id="fScore" class="severityRange" type="range" min="0" max="10" step="1" value="5" aria-label="وضعیت کلی پایان"></div><div class="stats" style="color:var(--muted);margin-top:0"><span>۰ = خیلی کم</span><span>۵ = متوسط</span><span>۱۰ = خیلی شدید</span></div>')
# final multi topic fields
old='<label>سه تغییر واقعی که در خودم مشاهده کردم</label><textarea id="f1" class="small" maxlength="2000"></textarea><label>سه آگاهی مهمی که به دست آوردم</label><textarea id="f2" class="small" maxlength="2000"></textarea>\n<label>سه اقدام مشخص برای ۳۰ روز آینده</label><textarea id="f3" class="small" maxlength="2000"></textarea><label>مهم‌ترین چیزی که هنوز نیاز به کار دارد</label><textarea id="f4" class="small" maxlength="2000"></textarea>'
new='''<label>سه تغییر واقعی که در خودم مشاهده کردم</label><select id="f1Count"><option value="3">۳ مورد</option></select><div id="f1Fields"></div>
<label>سه آگاهی مهمی که به دست آوردم</label><select id="f2Count"><option value="3">۳ مورد</option></select><div id="f2Fields"></div>
<label>سه اقدام مشخص برای ۳۰ روز آینده</label><select id="f3Count"><option value="3">۳ مورد</option></select><div id="f3Fields"></div>
<label>مهم‌ترین چیزی که هنوز نیاز به کار دارد</label><textarea id="f4" class="small" maxlength="2000"></textarea>'''
s=s.replace(old,new)
# book reader buttons exact titles with emojis prefix
s=s.replace('<div class="navrow"><button class="secondary" onclick="bookPrev()">← صفحه قبل</button><button class="secondary" onclick="showBooks(bookReturnTo)">کتابخانه</button><button class="secondary" onclick="show(bookReturnTo)">بازگشت</button><button class="primary" onclick="bookNext()">صفحه بعد →</button></div>', '<div class="navrow"><button class="primary" onclick="bookNext()">📖 مطالعه صفحه بعد</button><button class="secondary" onclick="bookPrev()">📘 مطالعه صفحه قبل</button><button class="secondary" onclick="showBooks(bookReturnTo)">📚 بازگشت به کتابخانه</button><button class="secondary" onclick="show(bookReturnTo)">🏠 بازگشت به داشبورد شخصی</button></div>')
# modal additions before copyright
anchor='<div id="copyrightModal"'
insert='''<button id="profileBackButton" class="floatingProfileBack hidden" onclick="requestProfileBack()">📝 بازگشت به فرم ثبت پرونده</button>
<div id="profileBackModal" class="validationModal hidden"><div class="validationCard"><span class="badge">بازگشت به پرونده</span><h2>قبل از بازگشت این نکته را بدان</h2><p class="muted">با بازگشت به فرم ثبت پرونده، اطلاعات مسیر طی‌شده آرشیو نمی‌شود و مسیر فعلی همچنان در حافظه همین برنامه باقی می‌ماند. اگر فقط می‌خواهی اطلاعات پرونده را ببینی یا اصلاح کنی، می‌توانی ادامه بدهی.</p><button class="primary" onclick="confirmProfileBack()">📝 رفتن به فرم ثبت پرونده</button><button class="secondary" onclick="closeProfileBack()">↩️ ادامه مسیر</button></div></div>
<div id="bookPreviewModal" class="bookPreviewModal hidden"><div class="bookPreviewCard"><span class="badge">مطالعه پیشنهادی · اختیاری</span><h2 id="bookPreviewTitle">مطالعه پیشنهادی امروز</h2><p id="bookPreviewMeta" class="muted"></p><article id="bookPreviewText" class="bookPreviewText"></article><button class="primary" onclick="goToSuggestedBook()">📚 رفتن به کتابخانه اختصاصی</button><button class="secondary" onclick="closeBookPreview()">↩️ فعلاً نمی‌خوانم</button></div></div>
'''
s=s.replace(anchor,insert+anchor)
# append anti copy css to body behavior via style in CSS
s=s.replace('body{margin:0;', 'html{-webkit-touch-callout:none}body{margin:0;user-select:none;-webkit-user-select:none;')
h.write_text(s,encoding='utf8')

p=root/'app.js'; js=p.read_text(encoding='utf8')
# default state lastView
js=js.replace('final:null,profileData:null,assessmentData:null,archive:[],pathId:null,startedAt:null', 'final:null,profileData:null,assessmentData:null,archive:[],pathId:null,startedAt:null,lastView:"home"')
# sanitize add lastView
js=js.replace('out.startedAt=typeof raw.startedAt==="string"?raw.startedAt:null;return out}', 'out.startedAt=typeof raw.startedAt==="string"?raw.startedAt:null;out.lastView=["home","howWorks","profile","assessment","dashboard","day","dailyResult","books","support","final","done","report","bookReader","archive"].includes(raw.lastView)?raw.lastView:"home";return out}')
# show save view and floating
js=js.replace('function show(id){["home","howWorks","profile","assessment","dashboard","day","dailyResult","books","support","final","done","report","bookReader","archive"].forEach(x=>$(x)?.classList.toggle("hidden",x!==id));window.scrollTo({top:0,behavior:"smooth"})}', 'function show(id){const ids=["home","howWorks","profile","assessment","dashboard","day","dailyResult","books","support","final","done","report","bookReader","archive"];ids.forEach(x=>$(x)?.classList.toggle("hidden",x!==id));const s=state();s.lastView=id;save(s);const back=$("profileBackButton");if(back)back.classList.toggle("hidden",["home","howWorks","profile"].includes(id));window.scrollTo({top:0,behavior:"smooth"})}')
# copyright acceptance resume
js=js.replace('function acceptCopyright(){localStorage.setItem("m28_copyright_ack","1");$("copyrightModal").classList.add("hidden")}', 'let pendingResume="home";function acceptCopyright(){$("copyrightModal").classList.add("hidden");show(pendingResume)}')
# validation helpers replace validDailyAnswer + add generic
js=js.replace('function validDailyAnswer(v){const x=String(v??"").trim();return x.length>=1&&x.length<=3000&&/^[آ-ی‌۰-۹٠-٩0-9\s]+$/.test(x)}', '''function validPersianText(v){const x=String(v??"").trim();return x.length>=1&&x.length<=3000&&/^[آ-ی‌\s.،؟!\-]+$/.test(x)}
function validDailyAnswer(v){return validPersianText(v)}
function attachPersianValidation(){document.querySelectorAll('input[type="text"],textarea').forEach(el=>{el.addEventListener('input',()=>{if(!validPersianText(el.value)&&el.value.trim()){el.setCustomValidity("فقط کلمات فارسی و نشانه‌های مجاز را وارد کنید.")}else el.setCustomValidity("")})})}
function makeCountFields(prefix,count=3,values=[]){const box=$(prefix+"Fields");if(!box)return;box.innerHTML="";for(let i=1;i<=count;i++){const ta=document.createElement("textarea");ta.className="small";ta.maxLength=2000;ta.id=prefix+"_"+i;ta.placeholder=`مورد ${fa(i)} را بنویس...`;ta.value=values[i-1]||"";box.appendChild(ta)}attachPersianValidation()}
function collectCountFields(prefix,count=3){const out=[];for(let i=1;i<=count;i++){const v=$(prefix+"_"+i)?.value.trim()||"";if(!validPersianText(v))return null;out.push(v)}return out}''')
# severity general
js=js.replace('function updateSeverity(v){const n=Math.max(0,Math.min(10,Number(normalizeDigits(v))||0));$("severityThumb").style.left=(n*10)+"%";$("severityText").textContent=', 'function updateScoreBar(id,v){const n=Math.max(0,Math.min(10,Number(normalizeDigits(v))||0));const th=$(id+"Thumb"),val=$(id+"Value");if(th)th.style.left=(n*10)+"%";if(val)val.textContent=fa(n)+" از ۱۰";return n}\nfunction updateSeverity(v){const n=updateScoreBar("severity",v);$("severityThumb").style.left=(n*10)+"%";$("severityText").textContent=')
# update severity now looks for severityThumb not severityThumb? updateScoreBar severityThumb yes, but value absent. Add severityValue markup? day HTML no value. patch HTML later.
# profile back funcs
js=js.replace('function closeValidation(){$("validationModal").classList.add("hidden")}', '''function closeValidation(){$("validationModal").classList.add("hidden")}
function requestProfileBack(){$("profileBackModal").classList.remove("hidden")}
function closeProfileBack(){$("profileBackModal").classList.add("hidden")}
function confirmProfileBack(){$("profileBackModal").classList.add("hidden");show("profile");restore()}
function closeBookPreview(){$("bookPreviewModal").classList.add("hidden")}
let suggestedBookTarget=null;function goToSuggestedBook(){if(!suggestedBookTarget)return;closeBookPreview();openBook(suggestedBookTarget.bookId,suggestedBookTarget.page,{day:suggestedBookTarget.day,reason:suggestedBookTarget.reason})}''')
# completeDay validate generic
js=js.replace('const answer=$("answer").value.trim(),score=$("dayScore").value.trim(),fb=$("dayFeedbackChoice").value;if(!validDailyAnswer(answer)||score===""||!fb||!validScore(score))', 'const answer=$("answer").value.trim(),score=$("dayScore").value.trim(),fb=$("dayFeedbackChoice").value;if(!validPersianText(answer)||score===""||!fb||!validScore(score))')
js=js.replace('if(!validDailyAnswer(answer))m.push("پاسخ یا تجربه امروز (فقط کلمات فارسی و عدد)")', 'if(!validPersianText(answer))m.push("پاسخ یا تجربه امروز (فقط کلمات فارسی و نشانه‌های مجاز)")')
# action example: split action into example
js=js.replace('function splitDayContent(d){if(d?.exerciseText||d?.actionText)return{exercise:String(d.exerciseText||""),action:String(d.actionText||"")};', 'function makeActionExample(action,title){const a=String(action||"").trim();if(!a)return"امروز فقط یک نمونه کوچک از این اقدام را در یک موقعیت واقعی انجام بده. مثال: یک موقعیت مشخص را انتخاب کن و همان اقدام را همان‌جا اجرا کن.";return `مثال عینی: فرض کن امروز در یک موقعیت واقعی «${title||"موضوع امروز"}» قرار گرفتی. به‌جای انجام کلی این توصیه، فقط همان یک اقدام را در همان موقعیت اجرا کن و نتیجه‌اش را مشاهده کن.`}\nfunction splitDayContent(d){if(d?.exerciseText||d?.actionText)return{exercise:String(d.exerciseText||""),action:makeActionExample(String(d.actionText||""),String(d.title||"").split("·")[0].trim())};')
# day severity markup via HTML later
# result next unique text
js=js.replace('$(''resultNext'').textContent=n===28?"روز ۲۸ کامل شد. اکنون ارزیابی نهایی فعال است.":"قبل از رفتن به روز بعد، نتیجه امروز را مرور کن و ببین چه چیزی از تمرین امروز برایت مهم‌تر بود.";', '$("resultNext").textContent=n===28?"روز ۲۸ کامل شد. اکنون ارزیابی نهایی فعال است.":nextStepText(n,rec);')
# above exact has single quotes? safer replace raw actual
js=js.replace('$('"'"'resultNext'"'"').textContent=n===28?"روز ۲۸ کامل شد. اکنون ارزیابی نهایی فعال است.":"قبل از رفتن به روز بعد، نتیجه امروز را مرور کن و ببین چه چیزی از تمرین امروز برایت مهم‌تر بود.";', '$("resultNext").textContent=n===28?"روز ۲۸ کامل شد. اکنون ارزیابی نهایی فعال است.":nextStepText(n,rec);')
# insert nextStepText before makeFeedback
js=js.replace('function makeFeedback(fb,score){', '''function nextStepText(n,rec){const texts=["امروز فقط یک نکته از تجربه‌ات را با خودت به فردا ببر؛ لازم نیست همه‌چیز را یک‌باره تغییر بدهی.","فردا به جای بیشتر فکر کردن، یک مشاهده دقیق‌تر انجام می‌دهی و آن را با تجربه امروز مقایسه می‌کنی.","گام بعدی تو کوچک است: ببین کدام بخش تمرین امروز در زندگی واقعی قابل استفاده‌تر بود.","فردا روی تشخیص محرک‌ها تمرکز کن؛ شناخت دقیق، پیش‌نیاز تغییر پایدار است.","آنچه امروز فهمیدی را به یک رفتار قابل مشاهده تبدیل کن؛ تغییر از عمل‌های کوچک ساخته می‌شود.","فردا یک انتخاب آگاهانه را تمرین می‌کنی؛ حتی اگر کوچک باشد، همان انتخاب مهم است.","به جای قضاوت خودت، داده جمع کن: چه چیزی کمک کرد و چه چیزی مانع شد؟","فردا قرار نیست کامل باشی؛ قرار است یک واکنش متفاوت را امتحان کنی.","امروز را با یک سؤال تمام کن: اگر یک درصد بهتر عمل کنم، دقیقاً چه کار می‌کنم؟","گام بعدی، تکرار کورکورانه نیست؛ تمرین را با تجربه واقعی خودت هماهنگ کن."];return texts[(Number(n)-1)%texts.length]}
function makeFeedback(fb,score){''')
# book preview function replace
js=js.replace('function openRecommendedBookForDay(n){const d=chooseDay(n);if(d.bookRec)openBook(d.bookRec.bookId,d.bookRec.page,{day:n,reason:d.bookRec.reason||"این بخش برای تعمیق موضوع امروز پیشنهاد شده است."});else showBooks()}', '''function openRecommendedBookForDay(n){const d=chooseDay(n);if(!d.bookRec)return;loadBookData(d.bookRec.bookId).then(b=>{const idx=Number(d.bookRec.page)-1;const page=b.pages[idx];if(!page)return; suggestedBookTarget={day:n,bookId:d.bookRec.bookId,page:Number(d.bookRec.page),reason:d.bookRec.reason||"این بخش برای تعمیق موضوع امروز پیشنهاد شده است."};$("bookPreviewTitle").textContent=`مطالعه پیشنهادی روز ${fa(n)}`;$("bookPreviewMeta").textContent=`جلد ${fa(d.bookRec.bookId)} · صفحه ${fa(d.bookRec.page)} · ${b.title}`;$("bookPreviewText").textContent=page.text||"";$("bookPreviewModal").classList.remove("hidden")}).catch(()=>{})}''')
# final finish/load/report dynamic
js=js.replace('function loadFinal(){const s=state();if(s.final){$("fScore").value=s.final.score??"";$("f1").value=s.final.f1||"";$("f2").value=s.final.f2||"";$("f3").value=s.final.f3||"";$("f4").value=s.final.f4||""}}', '''function loadFinal(){const s=state();if(s.final){$("fScore").value=s.final.score??"";const split=v=>String(v||"").split("\\n---\\n");makeCountFields("f1",3,split(s.final.f1));makeCountFields("f2",3,split(s.final.f2));makeCountFields("f3",3,split(s.final.f3));$("f4").value=s.final.f4||"";updateScoreBar("fScore",s.final.score)}}
function initFinalFields(){makeCountFields("f1",3);makeCountFields("f2",3);makeCountFields("f3",3);["f1Count","f2Count","f3Count"].forEach(id=>$(id)?.addEventListener("change",()=>makeCountFields(id.slice(0,2),Number($(id).value)||3)))}''')
js=js.replace('function finish(){const score=$("fScore").value.trim(),f1=$("f1").value.trim(),f2=$("f2").value.trim(),f3=$("f3").value.trim(),f4=$("f4").value.trim();', 'function finish(){const score=$("fScore").value.trim(),f1a=collectCountFields("f1",3),f2a=collectCountFields("f2",3),f3a=collectCountFields("f3",3),f4=$("f4").value.trim();const f1=f1a?f1a.join("\\n---\\n"):"",f2=f2a?f2a.join("\\n---\\n"):"",f3=f3a?f3a.join("\\n---\\n"):"";')
js=js.replace('if(!validScore(score)||!f1||!f2||!f3||!f4)', 'if(!validScore(score)||!f1a||!f2a||!f3a||!validPersianText(f4))')
js=js.replace('if(!f1)m.push("سه تغییر واقعی");if(!f2)m.push("سه آگاهی مهم");if(!f3)m.push("سه اقدام ۳۰ روز آینده");if(!f4)m.push("مهم‌ترین موضوع نیازمند کار")', 'if(!f1a)m.push("سه تغییر واقعی");if(!f2a)m.push("سه آگاهی مهم");if(!f3a)m.push("سه اقدام ۳۰ روز آینده");if(!validPersianText(f4))m.push("مهم‌ترین موضوع نیازمند کار")')
# restore f1/f2/f3 now loadFinal handles
# init behavior copyright every launch and resume last view
js=js.replace('function init(){restore();const s=state();if(!s.started)show("home");else if(!s.profile)show("profile");else if(!s.assessment)show("assessment");else if(s.completed.length>=28&&s.final)show("done");else showDashboard();update()}', '''function init(){restore();initFinalFields();attachPersianValidation();const s=state();pendingResume=s.lastView||(!s.started?"home":!s.profile?"profile":!s.assessment?"assessment":s.completed.length>=28&&s.final?"done":"dashboard");show(pendingResume);if($("copyrightModal"))$("copyrightModal").classList.remove("hidden");update();updateScoreBar("aScore",$("aScore")?.value||5);updateScoreBar("fScore",$("fScore")?.value||5);updateScoreBar("severity",$("dayScore")?.value||0)}''')
# DOM content listener replace
js=js.replace('document.addEventListener("DOMContentLoaded",()=>{if(localStorage.getItem("m28_copyright_ack")==="1")$("copyrightModal")?.classList.add("hidden");const range=$("dayScore");if(range)range.addEventListener("input",e=>updateSeverity(e.target.value))});', '''document.addEventListener("DOMContentLoaded",()=>{const ranges=[["dayScore","severity"],["aScore","aScore"],["fScore","fScore"]];ranges.forEach(([id,bar])=>$(id)?.addEventListener("input",e=>{if(bar==="severity")updateSeverity(e.target.value);else updateScoreBar(bar,e.target.value)}));document.addEventListener("contextmenu",e=>e.preventDefault());document.addEventListener("copy",e=>e.preventDefault());document.addEventListener("cut",e=>e.preventDefault());document.addEventListener("dragstart",e=>e.preventDefault());["visibilitychange","pagehide","beforeunload"].forEach(ev=>window.addEventListener(ev,()=>{try{const s=state();s.lastView=s.lastView||"home";save(s)}catch(e){}}));});''')
# remove requestBook old function and update buttons emojis by JS
js=js.replace('function requestBook(bookNumber){const s=state(),p=s.profileData||{},title=bookNumber===1?"از حقیقت تا واقعیت · جلد اول":"از حقیقت تا واقعیت · جلد دوم";const msg=`سلام. من ${p.name||"مراجع"} با کد مراجع ${p.code||"-"} هستم و درخواست دریافت «${title}» را دارم. لطفاً راهنمایی بفرمایید.`;window.open("https://t.me/Hypnotherapy_admin?text="+encodeURIComponent(msg),"_blank")}', '')
# append emoji mapper before load
js=js.replace('load();', '''function applyButtonEmojis(){const map=[["شروع مسیر","🚀"],["چگونه کار می‌کند","🌌"],["ادامه مسیر","▶️"],["کتابخانه","📚"],["عضویت درکانال","📣"],["پشتیبانی","🎧"],["ثبت","💾"],["نتیجه","📊"],["روز قبل","◀️"],["داشبورد","🏠"],["ارزیابی نهایی","📝"],["گزارش","📊"],["آرشیو","🗂️"],["مسیر تازه","🔄"],["بازگشت","↩️"],["متوجه شدم","✅"],["تهیه نسخه","🛒"],["مطالعه جلد","📖"]];document.querySelectorAll("button").forEach(b=>{let t=b.textContent.trim();if(!t||/^[^\p{L}\p{N}]/u.test(t))return;const hit=map.find(([k])=>t.includes(k));if(hit)b.textContent=hit[1]+" "+t});}applyButtonEmojis();load();''')
p.write_text(js,encoding='utf8')
# add severityValue to day
s=h.read_text(encoding='utf8')
s=s.replace('<label>شدت یا میزان درگیری امروز</label><div class="severityWrap"><div id="severityThumb"', '<label>شدت یا میزان درگیری امروز</label><div class="severityWrap"><div id="severityValue" class="severityValue">۰ از ۱۰</div><div id="severityThumb"')
h.write_text(s,encoding='utf8')
